# TEOF markdownlint config (Phase 0: unblock CI; tighten later)
default: true
# Temporarily relax the noisy ones to reduce churn:
MD013: false    # line length
MD041: false    # first line must be H1
MD036: false    # emphasis used as heading
MD034: false    # bare URLs/emails allowed (placeholders)
MD012: false    # multiple consecutive blank lines
MD022: false    # blank lines around headings
MD032: false    # blank lines around lists
MD031: false    # blank lines around fenced code blocks
MD040: false    # fenced code should declare language
# Keep a sane ordered list style:
MD029:
  style: "one"  # "1. 1. 1." preferred; renderer renumbers
