# Sensible, non-blocking house style for TEOF
default: true

MD013:            # line length
  line_length: 180
  code_blocks: false
  tables: false
  headings: false

MD041: false      # allow files without a top-level H1 (README already has one)

MD022:            # blanks around headings
  lines_above: 1
  lines_below: 1

MD024:            # duplicate headings allowed if nested differently
  allow_different_nesting: true

MD033:            # allow a few harmless HTML bits
  allowed_elements: ["br","sub","sup"]
