[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "teof"
version = "0.1.0a1"
description = "TEOF OCERS tooling (heuristic + ensemble)"
readme = "README.md"
requires-python = ">=3.9"

[project.scripts]
teof = "teof.cli:main"
teof-validate = "extensions.validator.teof_ocers_min:main"
teof-ensemble = "extensions.validator.scorers.ensemble_cli:main"

[tool.setuptools]
packages = ["extensions"]
include-package-data = true
