[project]
name = "ocers"
version = "0.1.0"
description = "OCERS: Observation–Coherence–Evidence–Result–Scope validator & scorer."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "OCERS Authors" }]
keywords = ["coherence", "alignment", "evaluation", "validator", "reasoning"]
dependencies = []

[project.scripts]
ocers-validate = "ocers.cli:main"
ocers-ensemble = "ocers.ensemble_cli:main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
