name: docs-hygiene

on:
  pull_request:
    paths:
      - 'docs/specs/**/*.md'

jobs:
  check-spec-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify specs have status + summary headers
        run: |
          fails=0
          for f in docs/specs/*.md; do
            if [ -f "$f" ]; then
              head -n 20 "$f" | grep -qi '^status:' || { echo "::error file=$f::Missing 'status:' header"; fails=1; }
              head -n 20 "$f" | grep -qi '^summary:' || { echo "::error file=$f::Missing 'summary:' header"; fails=1; }
            fi
          done
          exit $fails
