name: Label docs-only PRs
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs_only:
              - 'docs/**'
              - '!docs/teps/**'
              - '!docs/STATUS.md'
              - '!.github/**'
              - '!capsule/**'
              - '!extensions/**'
              - '!teof/**'
              - '!tests/**'
              - '!**/*.py'
              - '!**/*.yml'
      - name: Apply docs-trivial label
        if: steps.filter.outputs.docs_only == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: docs-trivial
