name: website
on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/pages.yml'
permissions:
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
