name: spec-hygiene

on:
  push:
    paths:
      - 'docs/specs/**/*.md'
  pull_request:
    paths:
      - 'docs/specs/**/*.md'

jobs:
  check-spec-headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify specs have status + summary headers
        run: |
          shopt -s nullglob
          fails=0
          found=0
          for f in docs/specs/*.md docs/specs/**/*.md; do
            [ -f "$f" ] || continue
            found=1
            head -n 40 "$f" | grep -qi '^status:' || { echo "::error file=$f::Missing 'status:' header"; fails=1; }
            head -n 40 "$f" | grep -qi '^summary:' || { echo "::error file=$f::Missing 'summary:' header"; fails=1; }
          done
          if [ "$found" -eq 0 ]; then
            echo "::notice::No spec files found under docs/specs/, skipping."
          fi
          exit $fails
