name: teof-selfprompt
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Seed self-prompt PR (docs-only)
        run: bash tools/selfprompt.sh
