name: teof-doc-automerge
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
permissions:
  pull-requests: write
  contents: read
jobs:
  check-and-automerge:
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge-docs')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Doctor (invariants)
        run: |
          chmod +x tools/doctor.sh
          ./tools/doctor.sh

      - name: Ensure PR is docs-only under docs/proposals/**
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const {owner, repo} = context.repo;
            const files = await github.paginate(github.rest.pulls.listFiles, {
              owner, repo, pull_number: pr.number, per_page: 100
            });
            const bad = files.filter(f => !f.filename.startsWith('docs/proposals/'));
            if (bad.length) {
              core.setFailed('Non-docs/proposals changes present: ' + bad.map(b=>b.filename).join(', '));
            } else {
              core.info('docs-only verified');
            }

      - name: Enable PR auto-merge (squash) when all checks pass
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
