# run from the repo root
cat > .github/workflows/teof-ci.yml <<'YML'
name: TEOF CI

on:
  push:
    paths:
      - 'capsule/**'
      - 'governance/**'
      - 'cli/**'
      - 'scripts/**'
      - 'docs/**'                  # examples/brief now lives under docs/
      - 'Makefile'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'capsule/**'
      - 'governance/**'
      - 'cli/**'
      - 'scripts/**'
      - 'docs/**'
      - 'Makefile'
      - '.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  show-tree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Show repo tree
        run: |
          set -euo pipefail
          sudo apt-get update -y >/dev/null 2>&1 || true
          sudo apt-get install -y tree >/dev/null 2>&1 || true
          echo "Top-level:" && tree -a -L 2 || true
          echo "Capsule subtree:" && tree -a -L 2 capsule || true
          echo "Examples subtree:" && tree -a -L 3 docs/examples/brief || true

  verify:
    needs: show-tree
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install (editable) + test deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest >/dev/null 2>&1 || true

      - name: Detect capsule baseline (and materialize current if needed)
        id: detect
        run: |
          set -euo pipefail
          CAP_ROOT="capsule"
          CUR="$CAP_ROOT/current"

          if [ -f "$CUR/hashes.json" ]; then
            echo "Using baseline: $CUR/hashes.json"
            echo "baseline_dir=$CUR" >> "$GITHUB_OUTPUT"
            echo "baseline_json=$CUR/hashes.json" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if compgen -G "$CAP_ROOT/v*/hashes.json" >/dev/null; then
            latest="$(ls -1d "$CAP_ROOT"/v*/ | sort -V | tail -n1)"
            latest="${latest%/}"
            echo "Materializing current/ from: $latest"
            mkdir -p "$CUR"
            cp -a "$latest"/. "$CUR"/
            if [ ! -f "$CUR/hashes.json" ] || [ ! -f "$CUR/capsule.txt" ]; then
              echo "::error file=$CUR::materialization failed: expected hashes.json and capsule.txt"
              exit 1
            fi
            echo "baseline_dir=$CUR" >> "$GITHUB_OUTPUT"
            echo "baseline_json=$CUR/hashes.json" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "::error::No capsule baseline found. Expected capsule/current/hashes.json or capsule/vX.Y/hashes.json"
          exit 1

      - name: Verify capsule hashes
        env:
          BASE_DIR: ${{ steps.detect.outputs.baseline_dir }}
          HFILE:    ${{ steps.detect.outputs.baseline_json }}
        run: |
          set -euo pipefail
          echo "Baseline dir:  $BASE_DIR"
          echo "Baseline JSON: $HFILE"
          python - <<'PY'
import os, json, hashlib, sys
base_dir = os.environ["BASE_DIR"]
hfile    = os.environ["HFILE"]

with open(hfile, 'r', encoding='utf-8') as f:
    expected = json.load(f)

def sha256_file(p):
    h = hashlib.sha256()
    with open(p,'rb') as f:
        for chunk in iter(lambda: f.read(8192), b''):
            h.update(chunk)
    return h.hexdigest()

ok = True
for rel, exp in expected.items():
    p = os.path.join(base_dir, rel)
    if not os.path.isfile(p):
        print(f"::error file={p}::missing file listed in hashes.json")
        ok = False
        continue
    got = sha256_file(p)
    if got != exp:
        print(f"::error file={p}::sha256 mismatch expected={exp} got={got}")
        ok = False
    else:
        print(f"OK {rel}")
sys.exit(0 if ok else 1)
PY

      - name: Validate anchors.json (schema + append-only + scope⊆baseline)
        env:
          HFILE:        ${{ steps.detect.outputs.baseline_json }}
          ANCHORS_PATH: governance/anchors.json
        run: |
          set -euo pipefail
          python - <<'PY'
import json, hashlib, os, sys, subprocess

P = os.environ["ANCHORS_PATH"]
if not os.path.isfile(P):
    print(f"Error: {P} not present."); sys.exit(1)

def sha256(b):
    import hashlib as _h
    h=_h.sha256(); h.update(b); return h.hexdigest()

cur_bytes = open(P,'rb').read()
cur_sha   = sha256(cur_bytes)
data      = json.loads(cur_bytes.decode('utf-8'))

required = ['version','policy','anchors','immutable_scope','events','releases']
missing  = [k for k in required if k not in data]
if missing:
    print("Error: missing keys in anchors:", ", ".join(missing)); sys.exit(1)
if data.get('policy') != 'append-only':
    print("Error: policy must be 'append-only'"); sys.exit(1)

# previous *change* to this file (not just HEAD~1)
rev_list = subprocess.check_output(['git','rev-list','-n','2','HEAD','--',P], text=True).splitlines()
if len(rev_list) >= 2:
    prev_change = rev_list[1]
    prev_bytes  = subprocess.check_output(['git','show', f'{prev_change}:{P}'])
    prev_sha    = sha256(prev_bytes)
    if prev_sha != cur_sha:
        last = data['events'][-1] if data.get('events') else None
        if not last or last.get('prev_content_hash') != prev_sha:
            print('Error: anchors events not append-only (last.prev_content_hash must equal sha256(previous content)).'); sys.exit(1)
        else:
            print('Append-only check: OK (against previous file change)')
else:
    print('Append-only check: first change to anchors; nothing to compare')

baseline = json.load(open(os.environ["HFILE"],'r',encoding='utf-8'))
scope    = set(data.get('immutable_scope',[]))
basekeys = set(baseline.keys())

missing = [p for p in scope if p not in basekeys]
if missing:
    print('Error: immutable_scope paths missing from baseline hashes.json:')
    for m in missing: print('  -', m)
    sys.exit(1)
if not scope:
    print('Warning: immutable_scope is empty')
elif scope != basekeys:
    extra  = sorted(scope - basekeys)
    absent = sorted(basekeys - scope)
    if extra:
        print('Warning: immutable_scope has extra paths not in baseline:', *extra, sep="\n  - ")
    if absent:
        print('Warning: immutable_scope omits baseline paths:', *absent, sep="\n  - ")

print(f'anchors sha256={cur_sha}  path={P}')
PY

      - name: Guardrails (.DS_Store / rings/ / legacy brief path)
        run: |
          set -euo pipefail
          if git ls-files | grep -q '\.DS_Store'; then
            echo "::error::.DS_Store files committed"; exit 1
          fi
          if git ls-files | grep -q '^rings/'; then
            echo "::error::deprecated path rings/ detected; use governance/"; exit 1
          fi
          if git ls-files | grep -q '^branches_thick/ocers_out/'; then
            echo "::error::legacy path branches_thick/ocers_out/ is forbidden"; exit 1
          fi
          echo "Guardrails OK"

      - name: Brief smoke (make brief or fallback to CLI)
        run: |
          set -euo pipefail
          mkdir -p artifacts/ocers_out
          if grep -qE '^[[:space:]]*brief:' Makefile 2>/dev/null; then
            OUT_ROOT="$GITHUB_WORKSPACE/artifacts" make brief
          else
            teof brief
          fi
          ls -l artifacts/ocers_out/latest/brief.json artifacts/ocers_out/latest/score.txt

      - name: Upload brief artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ocers_out
          path: artifacts/ocers_out/**

      - name: Optional tests (if repo has them)
        if: ${{ hashFiles('tests/**/*.py') != '' }}
        run: pytest -q

      - name: Enforce PR Objective line (PRs only)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          set -euo pipefail
          BODY="${{ github.event.pull_request.body }}"
          echo "Checking PR body for Objective line..."
          echo "$BODY" | grep -qiE 'Class=(Core|Trunk|Branch|Leaf);[[:space:]]*.*MinimalStep=' \
            || { echo "::error::Missing Objective line. Please add:"; \
                 echo "Class=<Core|Trunk|Branch|Leaf>; Why=…; MinimalStep=…; Direction=…"; exit 1; }
YML

ts=$(date -u +"%Y%m%dT%H%M%SZ")
BR="chore/ci-reset-${ts}"
git switch -c "$BR"
git add .github/workflows/teof-ci.yml
git commit -m "ci: reset workflow; verify capsule & anchors; brief smoke; artifacts; guards; cache"
git push -u origin "$BR"
echo "Open PR: https://github.com/octobrium/TEOF/compare/main...$BR"
