name: TEOF Auto Provenance (v1.5)

on:
  push:
    branches: ["**"]
    paths:
      - "capsule/v1.5/**"
    paths-ignore:
      - "capsule/v1.5/hashes.json"
      - "capsule/v1.5/PROVENANCE.md"

permissions:
  contents: write
  pull-requests: write

jobs:
  update-provenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update hashes + provenance (dry write)
        run: |
          python -u scripts/update_hashes.py \
            --root "." \
            --capsule-dir "capsule/v1.5" \
            --hashes "capsule/v1.5/hashes.json" \
            --provenance "capsule/v1.5/PROVENANCE.md"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "bot/provenance-${{ github.sha }}"
          title: "chore(provenance): refresh v1.5 hashes & provenance"
          body: |
            Automated PR to refresh `hashes.json` and append to `PROVENANCE.md` for capsule v1.5.

            - Source commit: `${{ github.sha }}`
            - Actor: `${{ github.actor }}`
          commit-message: "chore(provenance): refresh v1.5 hashes & provenance"
          add-paths: |
            capsule/v1.5/hashes.json
            capsule/v1.5/PROVENANCE.md
          labels: |
            auto
            provenance
            v1.5
          draft: false

      - name: No changes? Exit cleanly
        if: steps.cpr.outputs.pull-request-number == ''
        run: echo "No diffs to commit; skipping PR."
