name: TEOF Capsule Integrity

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Verify capsule hashes
        run: |
          python - <<'PY'
          import json, hashlib, pathlib, sys
          hashes = json.load(open('ops/hardening/hashes.json'))
          ok = True
          for path, expected in hashes.items():
              data = pathlib.Path(path).read_bytes()
              got = hashlib.sha256(data).hexdigest()
              if got != expected:
                  print(f"❌ FAIL {path}: {got} != {expected}")
                  ok = False
              else:
                  print(f"✅ OK {path}")
          if not ok:
              sys.exit(1)
          PY
