name: teof-ci

on:
  push:
    paths:
      - 'capsule/**'
      - 'governance/**'
      - 'cli/**'
      - 'scripts/**'
      - 'docs/**'
      - 'Makefile'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'capsule/**'
      - 'governance/**'
      - 'cli/**'
      - 'scripts/**'
      - 'docs/**'
      - 'Makefile'
      - '.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  show-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo tree
        run: |
          if ! command -v tree >/dev/null 2>&1; then
            sudo apt-get update -y >/dev/null 2>&1 || true
            sudo apt-get install -y tree >/dev/null 2>&1 || true
          fi
          tree -a -L 2 || true

  verify:
    runs-on: ubuntu-latest
    needs: show-tree
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml', '**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Repo health
        run: |
          chmod +x tools/bootstrap.sh tools/doctor.sh 2>/dev/null || true
          tools/bootstrap.sh
          tools/doctor.sh

      - name: Build brief
        run: |
          mkdir -p artifacts/ocers_out
          OUT_ROOT="$GITHUB_WORKSPACE/artifacts" make brief
          ls -l artifacts/ocers_out/latest/brief.json artifacts/ocers_out/latest/score.txt

      - name: Upload brief artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ocers_out
          path: artifacts/ocers_out/latest/
          if-no-files-found: warn
          retention-days: 7
